version: '3'
services:
  envoy:
    image: envoyproxy/envoy-alpine:latest
    ports:
    - "10000:10000"
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    environment:
    - loglevel=info
  authenticator:
    build: authenticator
    ports:
    - "8080:8080"
  authorizer:
    build: authorizer
  api:
    image: openresty/openresty:alpine
    command:
      - /bin/sh
      - -c
      - >
        echo '
        server {
          listen       8080;
          location / {
            content_by_lua_block {
              ngx.say("API is called!")
            }
          }
        }
        '
        > /etc/nginx/conf.d/default.conf
        && /usr/local/openresty/bin/openresty -g 'daemon off;'
