version: '3'
services:
  envoy:
    image: envoyproxy/envoy-alpine:latest
    ports:
    - "10000:10000"
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    environment:
    - loglevel=info
  authenticator:
    build: authenticator
    ports:
    - "8080:8080"
  authorizer:
    build: authorizer
  api:
    build: backend
