version: '3'
services:
  envoy:
    image: envoyproxy/envoy-alpine:latest
    ports:
    - "10000:10000"
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    environment:
    - loglevel=info
  authorizer:
    image: openresty/openresty:alpine
    command:
      - /bin/sh
      - -c
      - >
        echo '
        server {
          listen       8080;
          location /ok {
            return 200;
          }
          location /ng {
            return 401;
          }
        }
        '
        > /etc/nginx/conf.d/default.conf
        && /usr/local/openresty/bin/openresty -g 'daemon off;'
  api:
    image: openresty/openresty:alpine
    command:
      - /bin/sh
      - -c
      - >
        echo '
        server {
          listen       8080;
          location / {
            content_by_lua_block {
              ngx.say("API is called!")
            }
          }
        }
        '
        > /etc/nginx/conf.d/default.conf
        && /usr/local/openresty/bin/openresty -g 'daemon off;'
