version: '2'
services:
  web:
    image: openresty/openresty:alpine
    volumes:
      - ./index.html:/usr/local/openresty/nginx/html/index.html
    ports:
    - "8080:80"
  envoy-cors:
    image: envoyproxy/envoy-alpine:latest
    expose:
    - "80"
    - "8001"
    ports:
    - "8081:80"
    - "8001:8001"
    volumes:
    - ./envoy-cors.yaml:/etc/envoy/envoy.yaml
    environment:
    - loglevel=info
  api:
    image: openresty/openresty:alpine
    command:
    - /bin/sh
    - -c
    - >
      echo '
      server {
        listen       8080;
        access_log off;
        location / {
          content_by_lua_block {
            ngx.say("API is called!")
          }
        }
      }
      '
      > /etc/nginx/conf.d/default.conf
      && /usr/local/openresty/bin/openresty -g 'daemon off;'
